FROM openjdk:17-jdk

ARG MONGO_URL
ARG SECRET_KEY
ARG RABBIT_PORT
ARG RABBIT_USERNAME
ARG RABBIT_PASSWORD
ARG RABBIT_HOST
ENV MONGO_URL=${MONGO_URL}
ENV SECRET_KEY=${SECRET_KEY}
ENV RABBIT_PORT=${RABBIT_PORT}
ENV RABBIT_USERNAME=${RABBIT_USERNAME}
ENV RABBIT_PASSWORD=${RABBIT_PASSWORD}
ENV RABBIT_HOST=${RABBIT_HOST}

COPY ./build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]