version: '3'

services:
  color:
    build: .
    container_name: project-flow
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MONGO_URL=${MONGO_URL}
      - SECRET_KEY=${SECRET_KEY}
      - SOCKET_PORT=${SOCKET_PORT}