spring:
  data:
    mongodb:
      auto-index-creation: false
      authentication-database: admin
      uri: ${MONGO_URL}
      database: project-flow
jwt:
  secret: ${SECRET_KEY}
socket:
  port: ${SOCKET_PORT:8081}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG