spring:
  data:
    mongodb:
      auto-index-creation: false
      authentication-database: admin
      uri: ${MONGO_URL}
      database: project-flow
  profiles:
    active: local
jwt:
  secret: ${SECRET_KEY}
socket:
  port: ${SOCKET_PORT:8081}
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${BUCKET_NAME}